name: sendmail

on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Send an email via Gmail
        if: ${{ always() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          sender: gopinathsoundar06@gmail.com
          from: gopinathsoundar06@gmail.com
          to: gopinathsoundar06@gmail.com
          subject: "${{ github.job }} for ${{ github.repository }} has ${{ job.status }}"
          body: "${{ github.job }} for ${{ github.repository }} has ${{ job.status }} in workflow ${{ github.workflow }}"
          contentType: "text/plain"
